// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyBu6HfVunp76pg6Oxovs2IMNtM1sMkzo',
    appId: '1:892578122648:web:b84c3190ed480ae4ba79ed',
    messagingSenderId: '892578122648',
    projectId: 'autism-f1464',
    authDomain: 'autism-f1464.firebaseapp.com',
    storageBucket: 'autism-f1464.firebasestorage.app',
    measurementId: 'G-0B1ZEDGBM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnm9xUaGIhHXGKxpxXrLAcF6G4VOAZ3Dk',
    appId: '1:892578122648:android:e1d6134d4e887b3bba79ed',
    messagingSenderId: '892578122648',
    projectId: 'autism-f1464',
    storageBucket: 'autism-f1464.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzhwt79I7xzmBcDfnHamwl3BH9HPRzysg',
    appId: '1:892578122648:ios:f00cc8daf356c508ba79ed',
    messagingSenderId: '892578122648',
    projectId: 'autism-f1464',
    storageBucket: 'autism-f1464.firebasestorage.app',
    iosBundleId: 'com.example.autismFyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzhwt79I7xzmBcDfnHamwl3BH9HPRzysg',
    appId: '1:892578122648:ios:f00cc8daf356c508ba79ed',
    messagingSenderId: '892578122648',
    projectId: 'autism-f1464',
    storageBucket: 'autism-f1464.firebasestorage.app',
    iosBundleId: 'com.example.autismFyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyBu6HfVunp76pg6Oxovs2IMNtM1sMkzo',
    appId: '1:892578122648:web:7282e7e1c7495331ba79ed',
    messagingSenderId: '892578122648',
    projectId: 'autism-f1464',
    authDomain: 'autism-f1464.firebaseapp.com',
    storageBucket: 'autism-f1464.firebasestorage.app',
    measurementId: 'G-TFZRSD2PD1',
  );
}
